.TH "SIGHTTPD" 8 "May 2009" "SIG HTTP Server" "Annodex"

.SH NAME
sighttpd \- A stream ingress Hypertext Transfer Protocol Server

.SH SYNOPSIS

.B \fBsighttpd\fR \fIport\fR

.SH DESCRIPTION
.B sighttpd
is a stream ingress HTTP server.

.SH AUTHORS

sighttpd was written by Conrad Parker

Please report bugs to <conrad@metadecks.org>
