.TH "SIGHTTPD" 8 "May 2009" "SIG HTTP Server" "Annodex"

.SH NAME
sighttpd \- an HTTP server designed to work with realtime stream input.

.SH SYNOPSIS

.B \fBsighttpd\fR \fIport\fR

.PP
.SH DESCRIPTION
.B sighttpd
is a streaming HTTP server.

.SH OPTIONS
.PP
\fBsighttpd\fR accepts the following options:

.SS "Configuration file"
.IP "\-f \fBfilename\fR, \-\-config \fBfilename\fR" 10
Specify configuration filename [/etc/sighttpd/sighttpd.conf]
The syntax of this configuration file is specified in \fBsighttpd.conf\fP(5).

.PP
.SH "SEE ALSO"

.PP
\fBsighttpd.conf\fP(5)

.PP
.SH "DIAGNOSTICS"

.PP
.SH "BUGS"

.PP
Please report bugs to the author, conrad@metadecks.org
.PP
.SH "VERSION"

.PP
This man page is current for version 1.0.0 of sighttpd.
.PP
.SH "CREDITS"
.PP
sighttpd is distributed under the GNU General Public License.  See the file
COPYING for details.
.PP
A web site is available at
http://www.kfish.org/software/sighttpd/
.PP
We would be delighted to hear from you if you like this program.
.PP
.SH "AUTHOR"

.PP
sighttpd was written by Conrad Parker.
