.TH "SIGHTTPD" 8 "May 2009" "SIG HTTP Server" "Annodex"

.SH NAME
sighttpd \- A stream ingress Hypertext Transfer Protocol Server

.SH SYNOPSIS

.B \fBsighttpd\fR \fIport\fR

.PP
.SH DESCRIPTION
.B sighttpd
is a stream ingress HTTP server.

.SH OPTIONS
.PP
\fBsighttpd\fR accepts the following options:

.SS "Configuration file"
.IP "\-f \fBfilename\fR, \-\-config \fBfilename\fR" 10
Specify configuration filename [/etc/sighttpd/sighttpd.conf]

.PP
.SH CONFIGURATION

By default, sighttpd looks for the configuration file /etc/sighttpd/sighttpd.conf.
The following values are known:

.PP
.IP "\fBListen\fP"
The port number to listen on. This may be specified as a service name listed in
\fB/etc/services\fP.

.PP
.SH AUTHORS

sighttpd was written by Conrad Parker

Please report bugs to <conrad@metadecks.org>
